[package]
name = "rust-cpufreq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#todo look up dev deps for bindgen

[dependencies]
bindgen = "0.65.1"
